In [50]:
#Importer NumPy
import numpy as np

In [51]:
#Version de NumPy
np.__version__

'1.25.0'

In [52]:
#Premier scalaire : np.array()
scalaire = np.array(3+2j)
scalaire

array(3.+2.j)

In [53]:
#Premier tableau : np.array([])
tableau = np.array([1,2])
tableau

array([1, 2])

In [54]:
#Dimension d'un ndarray : array.ndim
print(tableau.ndim)
print(scalaire.ndim)

#ndarray de dimensions supérieures
scalaire = np.array(1,ndmin=1)
scalaire

1
0


array([1])

In [55]:
#Index d'un tableau à une dimension
print(tableau[0])

#Index dans un tableau à n dimensions
n=2
tableau_dim_deux = np.array([tableau,tableau[::-1]]) #Renverser le deuxième tableau
tableau_dim_deux[0,1]

1


2

In [75]:
#Récupérer une partie d'un tableau
arr = np.array([i for i in range(1,11)])
arr
print(arr[1:4])

#Récupérer les éléments d'un tableau depuis le troisième élément au dernier
print(arr[2:])

#Récupérer les éléments d'un tableau depuis le premier au troisième élément (exclu)
print(arr[:2])

#Récupérer les éléments d'un tableau depuis le premier au troisième élément (inclus)
print(arr[:3])

#Récupérer les éléments d'un tableau depuis le premier au troisième élément (inclus) dans le sens inverse
print(arr[-4:-1])

[2 3 4]
[ 3  4  5  6  7  8  9 10]
[1 2]
[1 2 3]
[7 8 9]


In [87]:
#Récupérer tous les 2 éléments d'un tableau
print(arr[::2])

[1 3 5 7 9]


In [104]:
#Récupérer les éléments d'un tableau à deux dimensions
tableau_deux = np.array([arr,arr[::-1]])
tableau_deux

print(tableau_deux[0,::-1]) #Renverser le premier tableau
print(tableau_deux[:,1]) #Récupère le deuxième élément de chaque tableau

[10  9  8  7  6  5  4  3  2  1]
[2 9]


In [110]:
#Copie et vue sur un array
arr[0]=1
copy_arr = arr.copy()
copy_arr

view_arr = arr.view()
view_arr[0]=5
print(copy_arr)
print(view_arr)
print(arr)

#copy() permet de copier un array sans modifier l'array original
#view() permet de copier et de modifier un array

[ 1  2  3  4  5  6  7  8  9 10]
[ 5  2  3  4  5  6  7  8  9 10]
[ 5  2  3  4  5  6  7  8  9 10]


In [115]:
#Joindre deux tableaux
tab = np.concatenate((copy_arr,view_arr))
tab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  5,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [116]:
#Rechercher un élément
np.where(tab==5)

(array([ 4, 10, 14], dtype=int64),)

In [118]:
#Trier un tableau
tab = np.sort(tab)
tab

array([ 1,  2,  2,  3,  3,  4,  4,  5,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10])